version: '3.8'

services:
  # Backend Services
  game-engine:
    build:
      context: ./backend/game-engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aviator
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  auth-service:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aviator
    depends_on:
      - db

  websocket-gateway:
    build:
      context: ./backend/websocket
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  analytics-service:
    build:
      context: ./backend/analytics
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - PYTHON_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aviator
    depends_on:
      - db

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Databases
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aviator
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
