# Nixpacks configuration for Aviator Server
[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @aviator/server prisma generate",
  "pnpm --filter @aviator/server build"
]

[start]
cmd = "cd apps/server && pnpm start"
