[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd apps/web && pnpm prisma generate",
  "pnpm run build"
]

[start]
cmd = "pnpm run start"
