[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd apps/server && pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
startCommand = "cd apps/web && pnpm start"

[[services]]
name = "server"
startCommand = "cd apps/server && pnpm start"
